# Site settings
title: 21cst
header-img: "img/green.jpg"
tagline: "cn"  
description: ""  
baseurl: ""  

# About/contact
owner: 
  name: "cst"
  email: cst4049@163.com
  bio: "smile and smile"

# Data
favicon: img/favicon.png

# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 8

timezone: Asia/Shanghai

# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "21cst"
      header-img: "img/green.jpg" # We don't want posts without a header image, that whould mean white on white
